# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MECA
                                 A QGIS plugin
 MECA - Modelo Estimativo de Consumo na Agricultura
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-04-16
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Marcus Barrozo/Companhia de Gestão dos Recursos Hídricos
        email                : @
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import Qgis, QgsFeature
from qgis.PyQt.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QProgressDialog
from qgis.core import QgsCoordinateReferenceSystem, QgsCoordinateTransform, QgsProject

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .meca_dialog import MECADialog
import os.path

#Import Libraries for the Model
import numpy as np

from osgeo import gdal, osr
import math
import xlwt
from xlwt import Alignment
import re

class MECA:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'MECA_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&MECA')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('MECA', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/meca/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Modelo Estimativo de Consumo na Agricultura'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&MECA'),
                action)
            self.iface.removeToolBarIcon(action)
    
    def select_layer (self):
        '''Select the mask layer'''
        try:
            mask = self.dlg.select_layercb.currentLayer()
            self.dlg.select_featurecb.setLayer(mask)
            
            if not mask:
                return None
            display_expression = mask.displayExpression()
            print(f"Display Expression: {display_expression}") 

            # Extract the field name (handling COALESCE function)
            match = re.search(r'COALESCE\(\s*"([^"]+)"', display_expression, re.IGNORECASE)
            if match:
                field_name = match.group(1)
                
            else:
                pass

            return mask, field_name
        
        except ValueError as e:
            QMessageBox.warning(self, "Erro", str(e))
        except Exception as e:
            QMessageBox.critical(self, "Erro", "Falha ao adicionar camada: {e}")
        print(mask)

    def select_feature (self):
        '''Select the feature from a feature list for the selected mask'''
        feature = self.dlg.select_featurecb.feature()
        
        if feature:
            geometry = feature.geometry()
            area = geometry.area()
            return {'geometry' : geometry, 'area' : area}
        else:
            return None
    
    def on_feature_selected (self, feature: QgsFeature):
        '''Retrieve the of the selected feature'''
        if feature is not None:
            layer, field_name = self.select_layer()
            
            if field_name is not None and field_name != "N/A":
                feature_name = feature.attribute(field_name)
                print(f"Selected feature: {feature_name}")
                
                self.field_name = feature_name

    def select_raster (self):
        '''Select the Raster bands B2;B3;B4;B8'''
        select_rasterb2 = self.dlg.select_rasterb2.currentLayer()
        
        if select_rasterb2:
            path_b2 = select_rasterb2.source()
            self.select_rasterb2 = path_b2
        else:
            QMessageBox.warning(self, "Camada Raster B2 não selecionada")
            pass

        select_rasterb3 = self.dlg.select_rasterb3.currentLayer()
        
        if select_rasterb3:
            path_b3 = select_rasterb3.source()
            self.select_rasterb3 = path_b3
        else:
            QMessageBox.warning(self, "Camada Raster B3 não selecionada")
            pass

        select_rasterb4 = self.dlg.select_rasterb4.currentLayer()
        
        if select_rasterb4:
            path_b4 = select_rasterb4.source()
            self.select_rasterb4 = path_b4
        else:
            QMessageBox.warning(self, "Camada Raster B4 não selecionada")
            pass

        select_rasterb8 = self.dlg.select_rasterb8.currentLayer()
        
        if select_rasterb8:
            path_b8 = select_rasterb8.source()
            self.select_rasterb8 = path_b8
        else:
            QMessageBox.warning(self, "Camada Raster B8 não selecionada")
            pass
    
    def output_directory (self):
        '''Save to write the raster outputs in a directory'''
        output_direc = self.dlg.rasterFile.filePath()
        if not output_direc:
            QMessageBox.warning(self, "Erro", "Selecione o diretório de saída")
            return None
        
        return output_direc
    
    '''From this point the code aims to the image processing and estimative calculations, the code is based on the SAFER algorithm combined with Hargreaves and Samani model'''
    
    def crop_raster (self):
        '''Read the raster bands and get projection'''
        import osgeo
        import osgeo.ogr as ogr

        #First: Take the raster from the select_raster method
        rasterB2 = self.select_rasterb2
        rasterB3 = self.select_rasterb3
        rasterB4 = self.select_rasterb4
        rasterB8 = self.select_rasterb8

        #Second: Read the raster
        b2 = gdal.Open(rasterB2, osgeo.gdal.GA_ReadOnly)
        b3 = gdal.Open(rasterB3, osgeo.gdal.GA_ReadOnly)
        b4 = gdal.Open(rasterB4, osgeo.gdal.GA_ReadOnly)
        b8 = gdal.Open(rasterB8, osgeo.gdal.GA_ReadOnly)
    
        #Obtain separated geotransform
        geotransform = b2.GetGeoTransform()
        x_min = geotransform[0]
        y_max = geotransform[3]
        x_max = x_min + geotransform[1] * b2.RasterXSize
        y_min = y_max + geotransform[5] * b2.RasterYSize
        

        #Third: Take and read the mask layer from select_layer method
        feat = self.select_feature()
        mask_geom = feat['geometry']
        if mask_geom is None:
            print("No geometry available")
            return
        
        masksimplified = mask_geom.simplify(tolerance = 0)
         
        if masksimplified.isEmpty():
            print("Mask feature has no geometry!")
            return
        
        #Fourth: Set offsets and dimensions for crop the raster
        maskExtent = masksimplified.boundingBox()
        mask_extent = [maskExtent.xMinimum(), maskExtent.yMinimum(), maskExtent.xMaximum(), maskExtent.yMaximum()]
        
        b2_transform = b2.GetGeoTransform()
        raster_origin_y = b2_transform[3]
        offset_x = int((mask_extent[0] + (b2_transform[1] / 2) - b2_transform[0]) / b2_transform[1])
        offset_y = int((raster_origin_y - mask_extent[3]) / abs(b2_transform[5]))
        width = int((mask_extent[2] - mask_extent[0]) / b2_transform[1])
        height = int((mask_extent[3] - mask_extent[1]) / abs(b2_transform[5]))

        #Fifth: Crop each band to bounding box of mask, turn into Numpy Array
        b2_crop = b2.ReadAsArray(offset_x, offset_y, width, height)
        b3_crop = b3.ReadAsArray(offset_x, offset_y, width, height)
        b4_crop = b4.ReadAsArray(offset_x, offset_y, width, height)
        b8_crop = b8.ReadAsArray(offset_x, offset_y, width, height)
        
        b2_crop_transform = (b2_transform[0] + offset_x * b2_transform[1], b2_transform[1], b2_transform[2], 
                            b2_transform[3] + offset_y * b2_transform[5], b2_transform[4], b2_transform[5])

        #Sixth: Mask the crop bands to the layer extension
        mask_layer = ogr.GetDriverByName('Memory').CreateDataSource("")
        mask_layer1 = mask_layer.CreateLayer("mask_layer", geom_type=ogr.wkbPolygon)
        feature = ogr.Feature(mask_layer1.GetLayerDefn())
        ogr_geom = ogr.CreateGeometryFromWkt(masksimplified.asWkt())
        feature.SetGeometry(ogr_geom)
        mask_layer1.CreateFeature(feature)
        feature.Destroy()

        mask_rasterize = gdal.GetDriverByName('MEM').Create('', width, height, 1, gdal.GDT_Byte)
        mask_rasterize.SetGeoTransform(b2_crop_transform)
        gdal.RasterizeLayer(mask_rasterize, [1], mask_layer1, burn_values=[1])
        mask_np = mask_rasterize.ReadAsArray()

        b2_mask = np.where(mask_np, b2_crop, 1)
        b3_mask = np.where(mask_np, b3_crop, 1)
        b4_mask = np.where(mask_np, b4_crop, 1)
        b8_mask = np.where(mask_np, b8_crop, 1)

        b2_mascara = b2_mask/10000
        b3_mascara = b3_mask/10000
        b4_mascara = b4_mask/10000
        b8_mascara = b8_mask/10000

        del b2
        del b3
        del b4 
        del b8

        return {
            'mask_extent' : mask_extent,
            'b2_transform' : b2_transform,
            'b2_crop_transform' : b2_crop_transform,
            'b2_mascara' : b2_mascara,
            'b3_mascara' : b3_mascara,
            'b4_mascara' : b4_mascara,
            'b8_mascara' : b8_mascara
        }
    
    def get_model_variables (self):
        '''Reads the gui user inputs and assigns to its model variables'''
        Tmax = float(self.dlg.tmax_line.text())
        Tmin = float(self.dlg.tmin_line.text())
        date = self.dlg.date_line.text()
        
        return {
            'Tmax' : Tmax,
            'Tmin' : Tmin,
            'date': date,
        }
    
    def Tmean (self):
        '''Gets the average temperature of the air, daily'''
        vrb = self.get_model_variables()
        
        Tmax = vrb['Tmax']
        Tmin = vrb['Tmin']

        Tmean = (Tmax + Tmin) / 2

        return Tmean
    
    def doy (self):
        '''Transform the datetime of image acquisition to day of year'''
        vrb = self.get_model_variables()
        date = vrb['date']
        
        try:
            from datetime import datetime
            date_obj = datetime.strptime(date, '%Y-%m-%d')
            
            doy = int(date_obj.strftime('%j'))
        
        except ValueError:
            self.dlg.doy_line.setText("Data inválida, use o formato 'AAAA-MM-DD'")
        
        return doy

    def albedo (self):
        '''Calculates the albedo based on the raster bands'''
        
        values = self.crop_raster()
        
        b2_mascara = values['b2_mascara']
        b3_mascara = values['b3_mascara']
        b4_mascara = values['b4_mascara']
        b8_mascara = values['b8_mascara']
        
        #albedo calculation
        top_alb = b2_mascara * 0.32 + b3_mascara * 0.26 + b4_mascara * 0.25 + b8_mascara + 0.17
        sur_alb = 0.6054 * top_alb + 0.0797
        hr_alb = 1.0223 * sur_alb + 0.0149
        

        #Write Raster to file
        adjusted_geotransform = values['b2_crop_transform']
        
        output_direc = self.output_directory()
        out_file = os.path.join(output_direc, 'albedo.tif')

        driver = gdal.GetDriverByName('GTiff')
        out_raster = driver.Create(out_file, hr_alb.shape[1], hr_alb.shape[0], 1, gdal.GDT_Float32)
        out_raster.SetGeoTransform(adjusted_geotransform)
        out_band = out_raster.GetRasterBand(1)
        out_band.WriteArray(hr_alb)
        
        srs = osr.SpatialReference()
        srs.ImportFromEPSG(4326)  # This is WGS84
        out_raster.SetProjection(srs.ExportToWkt())

        out_band.FlushCache()
        out_raster = None

        return hr_alb

    def ndvi (self):
        '''Calculates the Normalized Difference Vegetation Index based on the Red and Shortwave Infrared Bands'''
        
        #Call crop_raster to retrieve the derived values needed
        values = self.crop_raster()
        
        b4_mascara = values['b4_mascara']
        b8_mascara = values['b8_mascara']
        
        #NDVI calculation
        ndvi = (b8_mascara - b4_mascara) / (b8_mascara + b4_mascara)


        #Write Raster to file     
        adjusted_geotransform = values['b2_crop_transform']
        
        output_direc = self.output_directory()
        out_file = os.path.join(output_direc, 'ndvi.tif')
        
        driver = gdal.GetDriverByName('GTiff')
        out_raster = driver.Create(out_file, ndvi.shape[1], ndvi.shape[0], 1, gdal.GDT_Float32)
        out_raster.SetGeoTransform(adjusted_geotransform)
        out_band = out_raster.GetRasterBand(1)
        out_band.WriteArray(ndvi)

        srs = osr.SpatialReference()
        srs.ImportFromEPSG(4326)  # This is WGS84
        out_raster.SetProjection(srs.ExportToWkt())

        out_band.FlushCache()
        out_raster = None

        return ndvi
        
    def transform (self):
        '''Performs spatial transformations related to geographic coordinates and time'''
        
        values = self.crop_raster()
        b2_mascara = values['b2_mascara']
        b2_transform = values['b2_crop_transform']
        
        doy = self.doy()
        
        rows, cols = b2_mascara.shape
        row_indices, col_indices = np.meshgrid(np.arange(cols), np.arange(rows))
        
        long = b2_transform[0] + col_indices * b2_transform[1] + row_indices * b2_transform[2]
        lati = b2_transform[3] + col_indices * b2_transform[4] + row_indices * b2_transform[5]

        # Calculation related to the time
        map1 = (long / long.max()) * ((2 * math.pi) / 365) * (doy - 1)

        return {
            'long_crop' : long,
            'lati_crop' : lati,
            'map1' : map1
        }

    def Et (self):
        '''Calculates the Solar Zenith Angle'''
        values = self.transform()
        map1 = values['map1']
        
        Et = (0.000075 + 0.001868 * np.cos(map1) - 0.032077 * np.sin(map1) - 0.014615 * np.cos(2 * map1) - 0.04089 * np.sin(2 * map1))
        
        return Et
        
    def LAT (self):
        '''Local Apparent Time, for solar position calculation'''
        
        values = self.transform()
        long_crop = values['long_crop']
        Et = self.Et()

        LAT = (13 + (4 * long_crop / 60) + (Et / 60))

        return LAT
    
    def solDec (self):
        '''Calculates the Solar Declination'''
        
        values = self.transform()
        map1 = values['map1']
        
        Dec = 0.006918 - 0.399912 * np.cos(map1) + 0.70257 * np.sin(map1) + 0.006758 * np.cos(2 * map1) + 0.000907 * np.sin(2 * map1) - 0.002697 * np.cos(3 * map1) + 0.00148 * np. sin(3 * map1)

        return Dec
    
    def solElev (self):
        '''Calculates the solar elevation angle'''
        
        solDec = self.solDec()
        LAT = self.LAT()
        
        values = self.transform()
        lati = values['lati_crop']
        long = values['long_crop']
        
        lati_rad = np.deg2rad(lati)
        long_rad = np.deg2rad(long)
        
        solDec_rad = np.deg2rad(solDec)
        
        solTime = 15 * (LAT - 12)
        
        solar_elev_angle = np.rad2deg(np.arcsin(
            np.sin(solDec_rad) * np.sin(lati_rad) +
            np.cos(solDec_rad) * np.cos(lati_rad) * np.cos(np.deg2rad(solTime))
        ))
        
        return solar_elev_angle
    
    def Gsc (self):
        '''Calculates the Solar Constant'''
        
        Gsc = 0.0820
        
        return Gsc
    
    def dr (self):
        '''Defines Sun-Earth relative distance'''
        
        doy = self.doy()

        dr = 1 + 0.033 * np.cos(((2 * np.pi) / 365) * doy)

        return dr
    
    def Wsun (self):
        '''Calculates the Sunset Solar Angle Radiation'''

        values = self.transform()
        lati = values['lati_crop']
        Lati_rad = np.deg2rad(lati)
        
        solDec = self.solDec()

        Ws = np.arccos(-np.tan(Lati_rad) * np.tan(solDec))
        
        return Ws

    def Ra (self):
        '''Calculates the Solar Radiation based on Hargreaves and Samani (1982)'''

        values = self.transform()
        lati = values['lati_crop']
        Lati_rad = np.deg2rad(lati)

        Gsc = self.Gsc()
        dr = self.dr()
        Wsun = self.Wsun()
        solDec = self.solDec()


        Ra = ((24 * 60) / np.pi) * Gsc * dr * (Wsun * np.sin(Lati_rad) * np.sin(solDec) + np.cos(Lati_rad) * np.cos(solDec) * np.sin(Wsun))

        return Ra

    def RG (self):
        '''Estimates Global Radiation approximation by Beer-Lambert Law'''
        
        Ra = self.Ra()
        solElev = self.solElev()
        
        solElev_rad = np.deg2rad(solElev)

        atmospheric_transmittance = 0.74 #Mean value for Ceará by ANDRADE 2008.

        RG = Ra * atmospheric_transmittance**(1 / np.sin(solElev_rad))

        return RG

    def W (self):
        '''Calculates the solar time angle'''

        LAT = self.LAT()
        
        W = 15 * (LAT - 12) * (np.pi / 180)

        return W

    def cos_zwn (self):
        '''Calculates the cosine of the zenith angle'''
        
        values = self.transform()
        lati_crop = values['lati_crop']
        Dec = self.solDec()
        W = self.W()
        
        cos_zwn = np.sin(lati_crop * np.pi / 180) * np.sin(Dec) + np.cos(lati_crop * np.pi / 180) * np.cos(Dec) * np.cos(W)

        return cos_zwn

    def E0 (self):
        '''Calculates the Extraterrestrial Solar Radiation'''

        values = self.transform()
        map1 = values['map1']

        E0 = (1.00011 + 0.034221 * np.cos(map1) + 0.00128 * np.sin(map1) + 0.000719 * np.cos(2 * map1) + 0.000077 * np.sin(2 * map1))

        return E0

    def R (self):
        '''Calculates the Solar Radiation'''
        
        values = self.transform()
        lati_crop = values['lati_crop']
        
        Dec = self.solDec()
        Ws = self.Wsun()
        
        R = (Ws * np.sin(lati_crop * np.pi / 180) * np.sin(Dec)) + (np.cos(lati_crop * np.pi / 180) * np.cos(Dec) * np.sin(Ws))

        return R

    def RsTop (self):
        '''Calculates the Top of Atmosphere Solar Radiation'''

        values = self.crop_raster()
        b2_mascara = values['b2_mascara']
        
        E0 = self.E0()
        R = self.R()

        RsTop_aux = (1367 / np.pi) * E0 * R
        RsTop = RsTop_aux.reshape(b2_mascara.shape[0], b2_mascara.shape[1])

        return RsTop
    
    def RsTrans (self):
        '''Calculates the Transmissivity of Solar Radiation'''

        RG = self.RG()
        
        RsTop = self.RsTop()
        
        Transm = (RG * 11.6) / RsTop

        return Transm

    def Rn_coeff (self):
        '''Calculates the Net Radiation Coefficient'''
        
        Tmean = self.Tmean()
        
        Rn_coeff = 6.99 * Tmean - 39.99

        return Rn_coeff

    def Rn (self):
        '''Calculates the Net Radiation'''
        
        RG = self.RG()
        
        hr_alb = self.albedo()
        Rn_coeff = self.Rn_coeff()
        Transm = self.RsTrans()
        
        Rn = ((1 - hr_alb) * (RG * 11.6)) - (Rn_coeff * Transm)
        
        return Rn

    def Rn_MJ (self):
        '''Net Radiation in megajoules'''

        Rn = self.Rn()
        
        Rn_MJ = Rn / 11.6

        return Rn_MJ

    def slope (self):
        '''This function calculates the slope of the saturation vapour pressure-temperature curve'''
        
        Tmean = self.Tmean()

        slope = (4098 * (0.6108 * np.exp((17.27 * (Tmean)) / ((Tmean) + 237.3))) / ((Tmean) + 237.3) ** 2)

        return slope

    def LEeq (self):
        '''This function calculates the Latent Heat of Evaporation'''

        slope = self.slope()
        Rn = self.Rn()
        
        LEeq = (slope * Rn) / (slope + 0.066)
        
        return LEeq

    def close (self):

        slope = self.slope()
        slope.close()
        Rn_coeff = self.Rn_coeff()
        Rn_coeff.close()
        RsTop = self.RsTop()
        RsTop.close()
        RsTop_aux = self.RsTop_aux()
        RsTop_aux.close()
        R = self.R()
        R.close()
        Ws = self.Wsun()
        Ws.close()
        E0 = self.E0()
        E0.close()
        cos_zwn = self.cos_zwn()
        cos_zwn.close()
        W = self.W()
        W.close()
        Dec = self.Dec()
        Dec.close()
        LAT = self.LAT()
        LAT.close()
        Et = self.Et()
        Et.close()
        
    def RR (self):
        '''Calculates the Net Solar Radiation'''
        
        RG = self.RG()
        
        hr_alb = self.albedo()
        
        RR = hr_alb * RG
        
        return RR

    def Emiss_atm (self):
        '''Atmospheric Emissivity calculation'''

        Transm = self.RsTrans()
        
        Emiss_atm = 0.9364 * (((-1) * np.log(Transm)) ** 0.1135)
        Emiss_atm [Emiss_atm > 1] = 1
        
        return Emiss_atm

    def RLdown_wm2 (self):
        '''Calculates the Downward Longwave Radiation in Watts per square meter'''
        
        Tmean = self.Tmean()

        Emiss_atm = self.Emiss_atm()
        
        RLdown_wm2 = (Emiss_atm * 5.67 * (10 ** (-8)) * ((Tmean + 273.15) ** 4))
        
        return RLdown_wm2

    def RL_down (self):
        '''Downward Longwave Radiation'''
        
        RLdown_wm2 = self.RLdown_wm2()
        
        RL_down = RLdown_wm2 / 11.6
        
        return RL_down

    def RL_up (self):
        '''Upward Longwave Radiation'''
        
        RG = self.RG()
        
        RR = self.RR()
        RL_down = self.RL_down()
        Rn_MJ = self.Rn_MJ()
        
        RL_up = (RG - RR + RL_down - Rn_MJ)
        
        return RL_up

    def Esurf (self):
        '''Calculates the Surface Emissivity'''

        ndvi = self.ndvi()
        
        Esurf_r1 = np.copy(ndvi)
        Esurf_r1[ndvi < 0] = 1
        Esurf_r1[ndvi >= 0] = np.nan
        
        Esurf_r2 = 1.0035 + 0.0589 * np.log(ndvi)
        
        Esurf = np.where(np.isnan(Esurf_r1), Esurf_r2, Esurf_r1)

        return Esurf

    def TS24 (self):
        '''Calculates the 24-hour average Land Surface Temperature'''

        RL_up = self.RL_up()
        Esurf = self.Esurf()

        TS24 = ((RL_up * 11.6) / ((Esurf * 5.67) * (10 **(-8)))) ** (0.25)
        TS24 [TS24 < 273.15] = np.nan
        
        
        #Write Raster to file
        values = self.crop_raster()
        adjusted_geotransform = values['b2_crop_transform']
        
        output_direc = self.output_directory()
        out_file = os.path.join(output_direc, 'Temperatura de Superfície.tif')
        
        driver = gdal.GetDriverByName('GTiff')
        out_raster = driver.Create(out_file, TS24.shape[1], TS24.shape[0], 1, gdal.GDT_Float32)
        out_raster.SetGeoTransform(adjusted_geotransform)
        out_band = out_raster.GetRasterBand(1)
        out_band.WriteArray(TS24)

        srs = osr.SpatialReference()
        srs.ImportFromEPSG(4326)  # This is WGS84
        out_raster.SetProjection(srs.ExportToWkt())

        out_band.FlushCache()
        out_raster = None

        return TS24
        
    def kc (self):
        '''Calculates the Crop Coefficient'''
        
        TS24 = self.TS24()
        hr_alb = self.albedo()

        ndvi = self.ndvi()
        ndvi = np.where(ndvi <= 0, np.nan, ndvi)

        a = 1.8
        b = -0.008

        kc = np.exp(a + b * ((TS24 - 273.15) / (hr_alb * ndvi)))
        np.seterr(invalid = 'ignore')

        #Write Raster to file
        values = self.crop_raster()
        adjusted_geotransform = values['b2_crop_transform']
        
        driver = gdal.GetDriverByName('GTiff')
        
        output_direc = self.output_directory()
        out_file = os.path.join(output_direc, 'kc_origin.tif')
        
        out_raster = driver.Create(out_file, kc.shape[1], kc.shape[0], 1, gdal.GDT_Float32)
        out_raster.SetGeoTransform(adjusted_geotransform)
        out_band = out_raster.GetRasterBand(1)
        out_band.WriteArray(kc)
        srs = osr.SpatialReference()
        srs.ImportFromEPSG(4326)  # This is WGS84
        out_raster.SetProjection(srs.ExportToWkt())

        out_band.FlushCache()
        out_raster = None

        return kc

    def kc_scale (self):

        kc = self.kc()

        kc_min = np.nanmin(kc)
        kc_max = np.nanmax(kc)
        print(f"Kc min: {kc_min}, Kc max: {kc_max}")

        if kc_max <= 0.9:
            min = 0
            max = 0.3
        elif kc_max <= 1.8:
            min = 0
            max = 0.6
        elif kc_max <= 2.7:
            min = 0
            max = 0.9
        elif kc_max <= 3.6:
            min = 0
            max = 1.2
        
        if kc_max == 1.2:
            return kc
        else:
            kc_scale = ((kc - kc_min) / (kc_max - kc_min)) * (max - min) + min
        
        
        #Write Raster to file
        values = self.crop_raster()    
        adjusted_geotransform = values['b2_crop_transform']
        
        driver = gdal.GetDriverByName('GTiff')
        
        output_direc = self.output_directory()
        out_file = os.path.join(output_direc, 'coeficiente de cultura.tif')
        
        out_raster = driver.Create(out_file, kc_scale.shape[1], kc_scale.shape[0], 1, gdal.GDT_Float32)
        out_raster.SetGeoTransform(adjusted_geotransform)
        out_band = out_raster.GetRasterBand(1)
        out_band.WriteArray(kc_scale)
        srs = osr.SpatialReference()
        srs.ImportFromEPSG(4326)  # This is WGS84
        out_raster.SetProjection(srs.ExportToWkt())

        out_band.FlushCache()
        out_raster = None

        return kc_scale

    def HS (self):
        '''Calculates the Reference Evapotranspiration based on Hargreaves and Samani (1985)'''
        
        vrb = self.get_model_variables()
        Tmax = vrb['Tmax']
        Tmin = vrb['Tmin']
        
        Tmean = self.Tmean()

        Ra = self.Ra()

        ET0 = 0.0023 * (Tmax - Tmin)**0.5 * (Tmean + 17.8) * Ra * 0.408

        return ET0

    def ETr (self):
        '''Calculates the Evapotranspiration'''
        
        kc = self.kc_scale()
        ET0 = self.HS()
        
        ETr = kc * ET0
        
        #Write Raster to file
        values = self.crop_raster()
        adjusted_geotransform = values['b2_crop_transform']
        
        driver = gdal.GetDriverByName('GTiff')

        output_direc = self.output_directory()
        out_file = os.path.join(output_direc, 'Evapotranspiração.tif')
        
        out_raster = driver.Create(out_file, ETr.shape[1], ETr.shape[0], 1, gdal.GDT_Float32)
        out_raster.SetGeoTransform(adjusted_geotransform)
        out_band = out_raster.GetRasterBand(1)
        out_band.WriteArray(ETr)

        srs = osr.SpatialReference()
        srs.ImportFromEPSG(4326)  # This is WGS84
        out_raster.SetProjection(srs.ExportToWkt())

        out_band.FlushCache()
        out_raster = None

        return ETr

    def consumption (self):
        '''Calculates the volume of water consumed by the crop'''

        feat = self.select_feature()
        geometry = feat['geometry']
        ETr = self.ETr()
        output_direc = self.output_directory()

        source_crs = QgsCoordinateReferenceSystem(4326)
        target_crs = QgsCoordinateReferenceSystem(31984)
        transform = QgsProject.instance().transformContext()
        reproject = QgsCoordinateTransform(source_crs, target_crs, transform)

        # Reproject the geometry
        geometry.transform(reproject)

        # Calculate the area AFTER reprojection
        area_m2 = geometry.area() 
        area_ha = area_m2 / 10000

        print(f"Area in square meters (SIRGAS 2000): {area_m2}")
        print(f"Area in hectares: {area_ha}")

        consumption = ETr * area_m2  
        vol_m3 = consumption * 0.001
        
        #Used only to get the mean values
        #masked_vol = np.ma.masked_array(vol_m3, np.isnan(vol_m3)) 
        #mean_vol = np.average(masked_vol)
        #masked_et = np.ma.masked_array(ETr, np.isnan(ETr)) 
        #mean_et = np.average(masked_et)

        #Write Raster to file
        values = self.crop_raster()
        adjusted_geotransform = values['b2_crop_transform']
        
        driver = gdal.GetDriverByName('GTiff')

        output_direc = self.output_directory()
        out_file = os.path.join(output_direc, 'volume m³.tif')
        
        out_raster = driver.Create(out_file, vol_m3.shape[1], vol_m3.shape[0], 1, gdal.GDT_Float32)
        out_raster.SetGeoTransform(adjusted_geotransform)
        out_band = out_raster.GetRasterBand(1)
        out_band.WriteArray(vol_m3)

        srs = osr.SpatialReference()
        srs.ImportFromEPSG(4326)  # This is WGS84
        out_raster.SetProjection(srs.ExportToWkt())

        out_band.FlushCache()
        out_raster = None

        return vol_m3, area_ha, area_m2

    def mean_status (self):
        '''Retrieves the average of kc, ETr and vol_m3 for the status_report func'''
        kc = self.kc_scale()
        ETr = self.ETr()
        vol_m3, area_ha, area_m2 = self.consumption()

        masked_vol = np.ma.masked_array(vol_m3, np.isnan(vol_m3)) 
        mean_vol = np.average(masked_vol)
        
        masked_et = np.ma.masked_array(ETr, np.isnan(ETr)) 
        mean_et = np.average(masked_et)
        
        masked_kc = np.ma.masked_array(kc, np.isnan(kc)) 
        mean_kc = np.average(masked_kc)

        return mean_vol, mean_et, mean_kc
    
    def status_report (self):
        '''Generates a status report in Excel format'''
        
        layer = self.select_layer()
        vrb = self.get_model_variables()
        date = vrb['date']
        vol_m3, area_ha, area_m2 = self.consumption()
        mean_vol, mean_et, mean_kc = self.mean_status()
        output_direc = self.output_directory()
        
        feature_name = getattr(self, 'field_name', "N/A")
        
        workbook = xlwt.Workbook()
        worksheet = workbook.add_sheet('Relatório')
        
        def style (font_name='Arial', font_size=12, bold=False, align_horz=Alignment.HORZ_CENTER, align_vert=Alignment.VERT_CENTER, borders=None):
            font = xlwt.Font()
            font.name = font_name
            font.height = font_size * 20
            font.bold = bold
            style = xlwt.XFStyle()
            style.font = font
            alignment = Alignment()
            alignment.horz = align_horz
            alignment.vert = align_vert
            style.alignment = alignment
            if borders:
                style.borders = borders
            return style
        
        borders = xlwt.Borders()
        borders.left = borders.THIN
        borders.right = borders.THIN
        borders.top = borders.THIN
        borders.bottom = borders.THIN

        header_style = style(bold=True, align_horz=Alignment.HORZ_CENTER, align_vert=Alignment.VERT_CENTER, borders=borders)
        string_style = style(align_horz=Alignment.HORZ_CENTER)
        data_style = style(align_horz=Alignment.HORZ_RIGHT)
        unit_style = style(align_horz=Alignment.HORZ_RIGHT)

        worksheet.write_merge(0, 0, 0, 5, "Relatório MECA - " + date, header_style)
        worksheet.write(1, 0, "Usuário", header_style)
        worksheet.write(2, 0, feature_name, string_style)
        worksheet.write(1, 1, "KC", header_style)
        worksheet.write(2, 1, mean_kc, data_style)
        worksheet.write(1, 2, "ET (mm/dia)", header_style)
        worksheet.write(2, 2, mean_et, data_style)
        worksheet.write(1, 3, "Área (ha)", header_style)
        worksheet.write(2, 3, area_ha, data_style)
        worksheet.write(1, 4, "Área (m²)", header_style)
        worksheet.write(2, 4, area_m2, data_style)
        worksheet.write(1, 5, "Volume (m³/dia)", header_style)
        worksheet.write(2, 5, mean_vol, unit_style)
        
        worksheet.col(0).width = len("Usuário") * (256 * 3)
        worksheet.col(1).width = len("KC") * (256 * 3)
        worksheet.col(2).width = len("ET (mm/dia)") * (256 * 3)
        worksheet.col(3).width = len("Área (ha)") * (256 * 3)
        worksheet.col(4).width = len("Área (m²)") * (256 * 3)
        worksheet.col(5).width = len("Volume (m³/dia)") * (256 * 3)
        

        output_path = os.path.join(output_direc, "relatório MECA.xls")
        workbook.save(output_path)
        
        print(f"Relatório gerado em: {output_path}")

        return output_path

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = MECADialog()
        
        self.dlg.select_layercb.layerChanged.connect(self.select_layer)
        self.dlg.select_featurecb.featureChanged.connect(self.select_feature)
        self.dlg.select_featurecb.featureChanged.connect(self.on_feature_selected)
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()

        # See if OK was pressed
        if result:
            message = "O algoritmo MECA está rodando. Durante o processo o Qgis pode apresentar travamentos. Por favor, aguarde e não clique em nada!"
            self.iface.messageBar().pushMessage("Running Process", message, level=Qgis.Info, duration=1)

            progress = 30
            
            progress_diag = QProgressDialog("Running MECADialog", "Cancel", 0, progress, self.dlg)
            progress_diag.setWindowTitle("MECA")
            progress_diag.setWindowModality(QtCore.Qt.WindowModal)
            progress_diag.show()

            self.select_layer()
            self.select_raster()
            
            progress_diag.setValue(2)
            progress_diag.setLabelText("Alocando camada vetorial e rasters")

            #Read and reproject raster  
            self.crop_raster()
            
            progress_diag.setValue(3)
            progress_diag.setLabelText("Efetuando recorte de raster para a área solicitada")

            #Take from user the model variables 
            self.get_model_variables()
            
            progress_diag.setValue(4)

            self.albedo()
            self.ndvi()
            
            progress_diag.setValue(5)
            progress_diag.setLabelText("Calculando albedo e NDVI")

            self.transform()
            
            progress_diag.setValue(6)
            progress_diag.setLabelText("Efetuando transformações espaciais")

            self.Et()
            self.LAT()
            
            progress_diag.setValue(7)

            self.solDec()
            self.W()
            self.cos_zwn()
            
            progress_diag.setValue(8)

            self.E0()
            self.R()
            
            progress_diag.setValue(9)

            self.RsTop()
            self.RsTrans()
            self.Rn_coeff()
            self.Rn()
            self.Rn_MJ()
            
            progress_diag.setValue(10)

            self.slope()
            self.LEeq()
            
            progress_diag.setValue(15)
            progress_diag.setLabelText("Efetuando cálculos de declinação, radiação solar...")

            #self.close()
            
            self.RR()
            self.Emiss_atm()
            
            progress_diag.setValue(16)

            self.RLdown_wm2()
            self.RL_down()
            
            progress_diag.setValue(17)
            
            self.Esurf()
            self.TS24()
            
            progress_diag.setValue(18)
            progress_diag.setValue(19)
            progress_diag.setValue(20)
            progress_diag.setLabelText("Efetuando cálculos de radiação de ondas longas/curtas, emissividade atmosférica, emissividade da superfície, temperatura...")

            #Final Product - Evaporation coefficient (kc) and Evapotranspiration (ET)
            self.kc()
            self.kc_scale()
            self.ETr()
            self.consumption()
            self.status_report()

            progress_diag.setValue(40)
            progress_diag.setLabelText("Cálculos finais, obtendo coeficiente de cultura (Kc) e evapotranspiração (ETr)")

            #Load all the rasters directly in the project
            
            progress_diag.setValue(progress)
            progress_diag.setLabelText("Escrevendo resultados em raster")
            progress_diag.setLabelText("MECA finalizado!")
            progress_diag.close()

            #Display successful process message
            self.iface.messageBar().pushMessage(
            'SUCCESS', 'MECA was successful generated!',
            level = Qgis.Success, duration = 4)
        